config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  resources :ingredients

  post '/recipes/:id', to: 'ingredients#create'

  root "recipes#index"
  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	belongs_to :recipe
	
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	has_many :ingredients
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def create
		@ingredient = Ingredient.new
		@ingredient.name = params[:name]
		@ingredient.recipe_id = params[:id]
		if @ingredient.save
			respond_to do |format|
				format.html { redirect_to recipe_path(@recipe), notice: 'Ingredient added' }
				format.js { }
			end
		else
			respond_to do |format|
				format.html { redirect_to recipe_path(@recipe), notice: 'Something went wrong' }
				format.js { }
			end
		end
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		recipe = @ingredient.recipe
		@ingredient.destroy
		redirect_to recipe_path(recipe), notice: 'Ingredient deleted'
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		@recipes = Recipe.all
	end

	def show
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to recipe_path(@recipe), notice: "Recipe created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to recipe_path(@recipe), notice: 'Recipe updated'
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path
	end

	private

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def recipe_params
		params.require(:recipe).permit(:title, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/create.js.erb
// $('#ingredients').remove
$('#ingredients').prepend("<p> - <%= escape_javascript(@ingredient.name) %> <%= escape_javascript(link_to 'Remove', url_for(controller: 'ingredients', action: 'destroy', id: @ingredient.id), method: :delete, class: 'pull-right') %> </p>");

$("#reset-form").find('#name').val("");



//	"<%= escape_javascript(text_field_tag :name, nil, class: 'col-md-6') %>",
//	"<%= escape_javascript(link_to 'Add ingredient', new_ingredient_path, class: 'btn btn-primary', remote: true) %>")
// <%= text_field_tag :name, class: 'form-control' %>

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Recipes
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags 

%body
	%nav.navbar.navbar-default
		.container
			.navbar-header
				=link_to root_path do
					.navbar.navbar-brand
						= image_tag "recipe_icon"
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Add Recipe", new_recipe_path
				%li= link_to "Log Out", root_path

	.container
		= yield

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
	= f.text_field :title, class: 'form-control', placeholder: 'Name...'
	%br
	= f.text_area :description, class: 'form-control', placeholder: 'Description...'
	%br
	= f.submit class: 'btn btn-primary'
	%br
	%br

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

= link_to "Back", recipe_path(@recipe)

app/views/recipes/index.html.haml
#index-pics
	%h1 All Recipes
	- @recipes.each_slice(3) do |row|
		.row
		- row.each do |r|
			.col-sm-4
				.panel.panel-default
					.panel-heading
						.panel_title= link_to r.title, recipe_path(r)
					= link_to recipe_path(r) do
						.panel-body	
							= image_tag "bruschetta"
						.panel-footer

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

= link_to "Back", recipes_path

app/views/recipes/show.html.haml
.row
	.col-md-4#pic
		.panel.panel-default
			.panel-body= image_tag "bruschetta"

	.col-md-8
		.panel.panel-default
			.panel-heading
				.panel-title= @recipe.title
			.panel-body
				%p= @recipe.description
		= link_to "Delete", recipe_path(@recipe), method: :delete, class: 'btn btn-danger pull-right', data: { confirm: "Are you sure?" }
		= link_to "Edit", edit_recipe_path(@recipe), class: 'btn btn-info pull-right'
%br/
%br/
.row
	.col-md-6
		.panel.panel-default
			.panel-heading Ingredients
			.panel-body
				.col-xs-12#reset-form
					#ingredients
						- @recipe.ingredients.each do |i|
							%p
								\-
								= i.name
								= link_to "Remove", url_for(controller: 'ingredients', action: 'destroy', id: i.id), method: :delete, class: 'pull-right'
					= form_tag url_for(controller: 'ingredients', action: 'create', id: @recipe.id), remote: true do
						.col-md-8
							= text_field_tag :name, nil, class: 'form-control'
						= submit_tag 'Add ingredient', class: 'btn btn-primary pull-right'

	.col-md-6
		.panel.panel-default
			.panel-heading Directions
			.panel-body
				%p SKDASDKAKSD